timer = 0
btimer = irandom(10)
state = 0
attack = 0
firingspeed = 20
mouthx = 46
mouthy = 97
creator = 0
flip = 0
image_xscale = 2
image_yscale = 2
pieceoffset_x = 12
pieceoffset_y = 94
headtop = instance_create((x - pieceoffset_x), (y - pieceoffset_y), obj_bulletparent)
headtop.image_speed = 0.1
headtop.sprite_index = spr_spamton_laugh_top
headtop.depth = (depth - 2)
headtop.image_alpha = 0
headtop.image_xscale = 2
headtop.image_yscale = 2
reposition = 0
jumpy = irandom(1)
init = false
made = choose(0, 1)
doublecount = 0
inhalesfx = 0
effecttimer = 0
