destroyoffscreen = false
tolerance = 0
fadeInSpeed = 15
image_xscale = 2
image_yscale = 2
active = false
target = 3
damage = 10
beats = 0
beatsPrev = 0
lanesEndY = (cameray() + 150)
follow = -4
playSound = 1
