scr_makecaterpillar(obj_mainchara.x, obj_mainchara.y, 2, 0)
scr_makecaterpillar(obj_mainchara.x, obj_mainchara.y, 3, 1)
scr_makecaterpillar(obj_mainchara.x, obj_mainchara.y, 4, 2)
//scr_makecaterpillar(obj_mainchara.x, obj_mainchara.y, 2, 3)
//scr_makecaterpillar(obj_mainchara.x, obj_mainchara.y, 2, 4)