function scr_ascii_input_names() {
    global.asc_def[8] = stringsetloc("Backspace", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_5_0")
    global.asc_def[9] = stringsetloc("Tab", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_6_0")
    global.asc_def[12] = stringsetloc("Numpad 5 (nmlk off)", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_7_0")
    global.asc_def[13] = stringsetloc("Enter", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_8_0")
    global.asc_def[19] = stringsetloc("Pause", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_9_0")
    global.asc_def[20] = stringsetloc("Caps lock", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_10_0")
    global.asc_def[27] = stringsetloc("Escape", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_11_0")
    global.asc_def[32] = stringsetloc("Space", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_12_0")
    global.asc_def[33] = stringsetloc("Page up", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_13_0")
    global.asc_def[34] = stringsetloc("Page down", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_14_0")
    global.asc_def[35] = stringsetloc("End", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_15_0")
    global.asc_def[36] = stringsetloc("Home", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_16_0")
    global.asc_def[37] = stringsetloc("Left", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_17_0")
    global.asc_def[38] = stringsetloc("Up", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_18_0")
    global.asc_def[39] = stringsetloc("Right", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_19_0")
    global.asc_def[40] = stringsetloc("Down", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_20_0")
    global.asc_def[45] = stringsetloc("Insert", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_21_0")
    global.asc_def[46] = stringsetloc("Delete", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_22_0")
    global.asc_def[48] = "0"
    global.asc_def[49] = "1"
    global.asc_def[50] = "2"
    global.asc_def[51] = "3"
    global.asc_def[52] = "4"
    global.asc_def[53] = "5"
    global.asc_def[54] = "6"
    global.asc_def[55] = "7"
    global.asc_def[56] = "8"
    global.asc_def[57] = "9"
    global.asc_def[65] = "A"
    global.asc_def[66] = "B"
    global.asc_def[67] = "C"
    global.asc_def[68] = "D"
    global.asc_def[69] = "E"
    global.asc_def[70] = "F"
    global.asc_def[71] = "G"
    global.asc_def[72] = "H"
    global.asc_def[73] = "I"
    global.asc_def[74] = "J"
    global.asc_def[75] = "K"
    global.asc_def[76] = "L"
    global.asc_def[77] = "M"
    global.asc_def[78] = "N"
    global.asc_def[79] = "O"
    global.asc_def[80] = "P"
    global.asc_def[81] = "Q"
    global.asc_def[82] = "R"
    global.asc_def[83] = "S"
    global.asc_def[84] = "T"
    global.asc_def[85] = "U"
    global.asc_def[86] = "V"
    global.asc_def[87] = "W"
    global.asc_def[88] = "X"
    global.asc_def[89] = "Y"
    global.asc_def[90] = "Z"
    global.asc_def[91] = stringsetloc("Windows", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_59_0")
    global.asc_def[96] = stringsetloc("Numpad 0", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_60_0")
    global.asc_def[97] = stringsetloc("Numpad 1", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_61_0")
    global.asc_def[98] = stringsetloc("Numpad 2", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_62_0")
    global.asc_def[99] = stringsetloc("Numpad 3", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_63_0")
    global.asc_def[100] = stringsetloc("Numpad 4", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_64_0")
    global.asc_def[101] = stringsetloc("Numpad 5", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_65_0")
    global.asc_def[102] = stringsetloc("Numpad 6", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_66_0")
    global.asc_def[103] = stringsetloc("Numpad 7", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_67_0")
    global.asc_def[104] = stringsetloc("Numpad 8", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_68_0")
    global.asc_def[105] = stringsetloc("Numpad 9", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_69_0")
    global.asc_def[106] = stringsetloc("Numpad *", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_70_0")
    global.asc_def[107] = stringsetloc("Numpad +", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_71_0")
    global.asc_def[109] = stringsetloc("Numpad -", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_72_0")
    global.asc_def[110] = stringsetloc("Numpad .", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_73_0")
    global.asc_def[111] = stringsetloc("Numpad /", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_74_0")
    global.asc_def[112] = "F1"
    global.asc_def[113] = "F2"
    global.asc_def[114] = "F3"
    global.asc_def[115] = "F4"
    global.asc_def[116] = "F5"
    global.asc_def[117] = "F6"
    global.asc_def[118] = "F7"
    global.asc_def[119] = "F8"
    global.asc_def[120] = "F9"
    global.asc_def[121] = "F10"
    global.asc_def[122] = "F11"
    global.asc_def[123] = "F12"
    global.asc_def[144] = stringsetloc("Num Lock", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_87_0")
    global.asc_def[145] = stringsetloc("Scroll Lock", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_88_0")
    global.asc_def[160] = stringsetloc("Shift (left)", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_89_0")
    global.asc_def[161] = stringsetloc("Shift (right)", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_90_0")
    global.asc_def[162] = stringsetloc("Ctrl (left)", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_91_0")
    global.asc_def[163] = stringsetloc("Ctrl (right)", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_92_0")
    global.asc_def[164] = stringsetloc("Alt (left)", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_93_0")
    global.asc_def[165] = stringsetloc("Alt (right)", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_94_0")
    global.asc_def[186] = ";"
    global.asc_def[187] = "="
    global.asc_def[188] = ","
    global.asc_def[189] = "-"
    global.asc_def[190] = "."
    global.asc_def[191] = "?"
    global.asc_def[192] = "~"
    global.asc_def[219] = "["
    global.asc_def[220] = "\\"
    global.asc_def[221] = "]"
    global.asc_def[222] = "'"
    global.asc_def[16] = stringsetloc("Shift", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_107_0")
    global.asc_def[17] = stringsetloc("Control", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_108_0")
    global.asc_def[18] = stringsetloc("Alt", "scr_ascii_input_names_slash_scr_ascii_input_names_gml_109_0")
    return;
}