depth = obj_growtangle.depth
obj_growtangle.image_alpha = 0
minx = (obj_growtangle.x - (obj_growtangle.sprite_width / 2))
maxx = (obj_growtangle.x + (obj_growtangle.sprite_width / 2))
miny = (obj_growtangle.y - (obj_growtangle.sprite_height / 2))
maxy = (obj_growtangle.y + (obj_growtangle.sprite_height / 2))
suckx = (obj_growtangle.x + 100)
upper_sucky = (obj_growtangle.y - 40)
lower_sucky = (obj_growtangle.y + 40)
suckpower = 0
timer = 0
snapback = 0
target = 0
wait = 0
obj_battlesolid.image_xscale = 3
obj_battlesolid.image_yscale = 3
