image_xscale = 0
image_yscale = 0
image_alpha = 0.3
timer = 0
maxtimer = 15
growcon = 1
image_speed = 0
image_blend = merge_color(c_green, c_lime, 0.5)
target_angle = 0
fullgrow = 0
keep = 0
megakeep = 0
maxxscale = 2
maxyscale = 2
customBox = 0
init = false
spr_custom_box = sprite_index
